image: maven:3.3.9

clone:
  depth: full

pipelines:
  branches:
    develop:
    - step:
        name: Verify Code
        caches:
        - maven
        script:
        - mvn -B verify # -B batch mode makes Maven less verbose
    - step:
        name: Deploy to Staging
        deployment: staging
        script:
        - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_TEST.git $HEROKU_DEPLOY_BRANCH
    master:
    - step:
        name: Verify Code
        caches:
        - maven
        script:
        - mvn -B verify # -B batch mode makes Maven less verbose
    - step:
        name: Deploy to Production
        deployment: production
        script:
        - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $HEROKU_DEPLOY_BRANCH