# ==============
# = Data Source
# ==============
spring:
  datasource:
    url: ${CLEARDB_DATABASE_URL}
    platform: mysql
    username: ${CLEARDB_DATABASE_USERNAME}
    password: ${CLEARDB_DATABASE_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver

# ==================
# = Jpa / Hibernate
# ==================
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

# ===================
# = Logging Settings
# ===================
logging:
    level:
      root: INFO
      web: ERROR
      org.hibernate: INFO