SELECT CONTRIBUTOR.ID, CONTRIBUTOR.NAME, 
CONTRIBUTOR.BIRTH_DATE, 
IFNULL(CONTRIBUTOR.MARRIAGE_DATE,'-') AS MARRIAGE_DATE, 
CAMPAIGN.NAME, 
CONTRIBUTION.CREATION_DATE, 
CONTRIBUTION.AMOUNT/100
FROM CONTRIBUTOR
JOIN CONTRIBUTION ON CONTRIBUTION.ID_CONTRIBUTOR = CONTRIBUTOR.ID
JOIN CAMPAIGN ON CAMPAIGN.ID = CONTRIBUTION.ID_CAMPAIGN

WHERE CAMPAIGN.NAME LIKE '%A%' 
AND CONTRIBUTION.CREATION_DATE BETWEEN '2017-01-18' AND '2018-01-18'
/*COMEMORACAO DEVE-SE SER TRATADO NO JAVA, CASO A DATA DE CASAMENTO OU ANIVERSARIO ESTEJA DENTRO DO MES ATUAL
PODE ACONTECER DE SER ANIVERSARIO E CASAMENTO NO MESMO MÊS*/;
