/*LISTAGEM CONTRIBUINTES*/
select CONTRIBUTOR.ID, CONTRIBUTOR.NAME, BEAD.IDENTIFICATION_NUMBER as BEAD, CAMPAIGN.NAME
from CONTRIBUTOR
inner join BEAD on BEAD.ID_CONTRIBUTOR = CONTRIBUTOR.ID
inner join CAMPAIGN on  CAMPAIGN.ID = BEAD.ID_CAMPAIGN

where CONTRIBUTOR.NAME like '%o%'
and CAMPAIGN.NAME = 'Dizimo'
and BEAD.IDENTIFICATION_NUMBER = 1
order by CONTRIBUTOR.CREATION_DATE desc;

/*EDICAO CONTRIBUINTE*/
select * from contributor where id = 1;

/*OBTEM TABELA TALAO*/
SELECT BEAD.IDENTIFICATION_NUMBER AS BEAD, CAMPAIGN.NAME
FROM BEAD
inner JOIN CAMPAIGN ON CAMPAIGN.ID = BEAD.ID_CAMPAIGN
where BEAD.ID_CONTRIBUTOR = 1;

select * from contribution;

(SELECT BEAD.IDENTIFICATION_NUMBER, bead.ID_CONTRIBUTOR, contribution.AMOUNT FROM BEAD 
LEFT JOIN contribution ON BEAD.ID_CONTRIBUTOR=contribution.ID_CONTRIBUTOR)
UNION
(SELECT BEAD.IDENTIFICATION_NUMBER, bead.ID_CONTRIBUTOR, contribution.AMOUNT FROM BEAD
RIGHT JOIN contribution ON BEAD.ID_CONTRIBUTOR=contribution.ID_CONTRIBUTOR)