
/*ULTIMOS LANCAMENTOS*/
SELECT CONTRIBUTOR.NAME, CONTRIBUTION.AMOUNT/100 AS CONTRIBUTION, CAMPAIGN.NAME AS CAMPAIGN, CONTRIBUTION.CREATION_DATE, IFNULL(CONTRIBUTOR.TELEPHONE, CONTRIBUTOR.CELLPHONE) AS CONTATO
FROM CONTRIBUTOR 
INNER JOIN CONTRIBUTION ON CONTRIBUTION.ID_CONTRIBUTOR = CONTRIBUTOR.ID
INNER JOIN CAMPAIGN ON CAMPAIGN.ID = CONTRIBUTION.ID_CAMPAIGN

WHERE CONTRIBUTOR.NAME LIKE '%A%' 
AND CAMPAIGN.NAME = 'DIZIMO'
AND CONTRIBUTION.CREATION_DATE BETWEEN '2017-01-18' AND '2018-01-18'
ORDER BY CONTRIBUTION.CREATION_DATE DESC;

/*ULTIMOS CADASTROS*/
SELECT CONTRIBUTOR.NAME, IFNULL(CONTRIBUTOR.TELEPHONE, '-') AS TELEPHONE, IFNULL(CONTRIBUTOR.CELLPHONE, '-') AS CELLPHONE, CONTRIBUTOR.CREATION_DATE
FROM CONTRIBUTOR
WHERE CONTRIBUTOR.NAME LIKE '%A%'
/*AND CONTRIBUTOR.TELEPHONE = '1999144484'*/
/*AND CONTRIBUTOR.CELLPHONE = '19990783372'*/
ORDER BY CONTRIBUTOR.CREATION_DATE DESC;

/*SOMATORIA*/
SELECT CAMPAIGN.NAME AS CAMPAIGN, DATE_FORMAT(CONTRIBUTION.CREATION_DATE, '%M / %Y') AS 'MES/ANO', SUM(CONTRIBUTION.AMOUNT/100) AS TOTAL
FROM CAMPAIGN
INNER JOIN CONTRIBUTION ON CONTRIBUTION.ID_CAMPAIGN = CAMPAIGN.ID
GROUP BY CAMPAIGN.NAME, DATE_FORMAT(CREATION_DATE, '%M / %Y')
ORDER BY DATE_FORMAT(CONTRIBUTION.CREATION_DATE, '%M / %Y') DESC;
